//Listado de constantes para todo el proyecto
const constantesTrabajos = {
    TITULO_APLICACION : 'Trabajos de Graduación',
    MODIFICACION_TRABAJO : 'Modificación de trabajo',
    FINALIZACION_TRABAJO : 'Finalización de trabajo',
    BAJA_TRABAJO : 'Baja de trabajo',
    MENSAJE_MODIFICACION : 'Se modificó el trabajo ',
    MENSAJE_FINALIZACION : 'Se finalizó el trabajo ',
    MENSAJE_BAJA : 'Se dió de baja el trabajo ',
    TITULO : 'Título',
    AREAS : 'Areas',
    PRESENTACION : 'Presentación',
    APROBACION : 'Aprobación',
    FINALIZACION : 'Finalización',
    TUTORES : 'Tutores',
    TUTOR : 'Tutor',
    COTUTORES : 'Cotutores',
    COTUTOR : 'Cotutor',
    TUTOR_COTUTOR : 'Tutor y Cotutor',
    JURADO : 'Jurado',
    ALUMNOS : 'Alumnos',
    ALUMNO : 'Alumno',
    APEYNOM : 'Apellido y nombre',
    DESDE : 'Desde',
    HASTA : 'Hasta',
    RAZON : 'Razón',
    DNI : 'DNI',
    CX : 'CX',
    DURACION : 'Duración',
    HARDWARE : 'Hardware',
    SOFTWARE : 'Software',
    REDES : 'Redes',
    CAMBIAR_TUTOR : 'Cambiar tutor',
    CAMBIAR_TUTOR_RAZON : 'Ingrese la razón por la que se cambia el tutor',
    TUTOR_ACTIVO : 'Sólo puede haber un tutor activo (uno solo que no tenga fecha de finalización)',
    TUTOR_ACTIVO2 : 'No puede haber más de un tutor activo (con fecha de finalización)',
    QUITAR_TUTOR : 'Quitar tutor',
    CAMBIAR_COTUTOR : 'Cambiar cotutor',
    CAMBIAR_COTUTOR_RAZON : 'Ingrese la razón por la que se cambia el cotutor',
    COTUTOR_ACTIVO : 'Sólo puede haber un cotutor activo (uno solo que no tenga fecha de finalización)',
    COTUTOR_ACTIVO2 : 'No puede haber más de un cotutor activo (con fecha de finalización)',
    QUITAR_COTUTOR : 'Quitar cotutor',
    CAMBIAR_JURADO : 'Cambiar jurado',
    CAMBIAR_JURADO_RAZON : 'Ingrese la razón por la que se cambia el jurado',
    JURADO_ACTIVO : 'Debe haber 3 miembros del jurado activos (sólo 3 que tengan fecha de finalización)',
    JURADO_ACTIVO2 : 'Sólo pueden haber 3 miembros del jurado activos (sólo 3 que no tengan fecha de finalización)',
    QUITAR_JURADO : 'Quitar jurado',
    AGREGAR_ALUMNO : 'Agregar alumno',
    QUITAR_ALUMNO : 'Quitar alumno',
    FINALIZAR_ALUMNO_RAZON : 'Ingrese la razón por la que finaliza el alumno su participación en el trabajo',
    ALUMNO_ACTIVO : 'Ningún alumno sigue en el trabajo',
    MODIFICAR_RAZON : 'Modificar razón',
    FINALIZAR_TRABAJO : 'Finalizar trabajo',
    FINALIZAR_ALUMNO : 'Finalizar alumno',
    DAR_DE_BAJA : 'Baja',
    CANCELAR : 'Cancelar',
    ACEPTAR : 'Aceptar',
    TITULO_INVALIDO : 'El título del trabajo es inválido',
    TITULO_REPETIDO : 'Ya existe un trabajo con ese título',
    DURACION_INVALIDA : 'La duración es inválida',
    AREAS_INVALIDAS : 'El trabajo no tiene asignada ningún área',
    FECHA_PRESENTACION_INVALIDA : 'La fecha de presentación es inválida',
    FECHA_APROBACION_INVALIDA : 'La fecha de aprobación es inválida',
    FECHA_APROBACION_ANTERIOR_FINALIZACION : 'La fecha de aprobación debe ser igual o posterior a la de presentación',
    FECHA_FINALIZACION_ANTERIOR_APROBACION : 'La fecha de finalización debe ser posterior a la de aprobación',
    TUTOR_INVALIDO : 'El trabajo no tiene asignado un tutor, o al menos un tutor es inválido',
    COTUTOR_INVALIDO2 : 'Al menos un cotutor es inválido',
    COTUTOR_INVALIDO : 'El tutor y cotutor son las mismas personas',
    JURADO_INCOMPLETO : 'El jurado está incompleto',
    JURADO_INVALIDO : 'Al menos un miembro del jurado es inválido',
    JURADO_DUPLICADO : 'El jurado debe estar formado por profesores diferentes',
    TUTOR_ES_JURADO : 'El tutor no puede formar parte del jurado',
    COTUTOR_ES_JURADO : 'El cotutor no puede formar parte del jurado',
    ALUMNOS_INCOMPLETO : 'El trabajo no tiene alumnos',
    ALUMNO_INVALIDO : 'Al menos un alumno es inválido',
    ALUMNOS_DUPLICADOS : 'El trabajo tiene alumnos repetidos',
    ALUMNO_EN_OTRO_TRABAJO : 'Uno o más alumnos ya están en otro trabajo',
    OK : 'OK',
    DADO_DE_BAJA : 'Dado de baja',
    MENSAJE_CONFIRMAR_BORRADO : '¿Confirma el borrado del trabajo: ',
    MENSAJE_CONFIRMAR_FINALIZACION : '¿Confirma la finalización del trabajo: ',
    MENSAJE_CONFIRMAR_MODIFICACION : '¿Confirma la modificación del trabajo: ',
    MENSAJE_CONFIRMAR_BAJA : '¿Confirma la baja del trabajo: ',
    ANIO_PRIMER_TRABAJO : 2013
}

const constantesAlumnos = {
    APELLIDOS : 'Apellidos',
    NOMBRES : 'Nombres',
    DNI : 'DNI',
    CX : 'CX',
    ACEPTAR : 'Aceptar',
    CANCELAR : 'Cancelar',
    MENSAJE_CONFIRMAR_MODIFICACION: '¿Confirma la modificación del alumno?',
    MENSAJE_CONFIRMAR_BORRADO: '¿Confirma el borrado del alumno: ',
    APELLIDOS_INVALIDO : 'El apellido del alumno es inválido',
    NOMBRES_INVALIDO : 'El nombre del alumno es inválido',
    DNI_INVALIDO : 'El DNI del alumno es inválido',
    DNI_REPETIDO : 'Ya existe un alumno con ese DNI',
    CX_REPETIDO : 'Ya existe un alumno con ese CX',
    NUEVO_ALUMNO : 'Nuevo alumno',
    MENSAJE_NUEVO_ALUMNO : 'Se creó el alumno',
    OK : 'OK',
    MENSAJE_MODIFICACION : 'Alumno modificado con éxito',
    ERROR_BORRAR : 'No se puede borrar el alumno porque está en un trabajo',
    FILTRAR_POR : 'Filtrar por',
    FILTRAR_POR_TODOS : 'Todos los alumnos',
    FILTRAR_POR_SIN_FINALIZAR : 'Trabajos sin finalizar',
    FILTRAR_POR_FINALIZADOS : 'Trabajos finalizados'
}

const constantesProfesores = {
    APELLIDOS : 'Apellidos',
    NOMBRES : 'Nombres',
    DNI : 'DNI',
    CARGO : 'Cargo',
    ACEPTAR : 'Aceptar',
    CANCELAR : 'Cancelar',
    MENSAJE_CONFIRMAR_MODIFICACION: '¿Confirma la modificación del profesor?',
    MENSAJE_CONFIRMAR_BORRADO: '¿Confirma el borrado del profesor: ',
    APELLIDOS_INVALIDO : 'El apellido del profesor es inválido',
    NOMBRES_INVALIDO : 'El nombre del profesor es inválido',
    DNI_INVALIDO : 'El DNI del profesor es inválido',
    DNI_REPETIDO : 'Ya existe un profesor con ese DNI',
    NUEVO_PROFESOR : 'Nuevo profesor',
    MENSAJE_NUEVO_PROFESOR : 'Se creó el profesor',
    OK : 'OK',
    MENSAJE_MODIFICACION : 'Profesor modificado con éxito',
    ERROR_BORRAR : 'No se puede borrar el profesor porque está en un trabajo',
}

export {
    constantesTrabajos, constantesAlumnos, constantesProfesores
}